import camera from "../assets/images/Camera.png";
import compass from "../assets/images/Compass.png";
import preview from "../assets/images/Diamond.png";
import flag from "../assets/images/Flag.png";

export const points = {
  routePoints: [
    {
      coordinates: [56.3038, 43.9387],
      id: 3040,
      title: "Ресторан Folk2",
      description: "jkzdnfvn",
      content: "Кажется, время завтрака?2",
      type: "route",
      preview_image: preview,
    },
    {
      coordinates: [56.3007, 43.9404],
      id: 41454,
      title: "Ресторан Folk",
      description: "jkzdnfvn",
      content: "Кажется, время завтрака?",
      type: "route",
      preview_image: preview,
    },
    {
      coordinates: [56.2929, 43.9352],
      id: 193624,
      title: "Ресторан Folk2<dsdf",
      description: "jkzdnfvn",
      content: "Спектакль-променад по Старо-Татарской слободе",
      type: "excursion",
      preview_image: preview,
    },
    {
      coordinates: [56.31155000000001, 44.00583],
      id: 2412,
      title: "Ресторан Folk2<dsdf",
      description: "jkzdnfvn",
      content: "Кажется, время завтрака?2<df<dfb",
      type: "promo",
      preview_image: preview,
    },
    {
      coordinates: [56.2855, 43.9306],
      id: 2415,
      title: "Ресторан Folk2<d<dfbdfbsdf",
      description: "jkzdnfvn",
      content: "Кажется, время завтрака?2<df<dfbdfbdfb",
      type: "partners",
      preview_image: preview,
    },
    {
      coordinates: [56.322066666666665, 44.01324666666667],
      id: 2499,
      title: "Ресторан Folk2<dzdfbzdfb<dfbzdfbsdf",
      content: "Кажется, время завтрака?2<dfzdfbzdfbzdfbdgb<dfb",
      type: "route",
      preview_image: preview,
    },
    {
      coordinates: [56.3389, 43.8809],
      id: 2505,
      title: "Ресторан Folk288888<dzdfbzdfb<dfbzdfbsdf",
      description: "jkzdnfvn",
      content: "Кажется, время завтрака?2888888<dfzdfbzdfbzdfbdgb<dfb",
      type: "route",
      preview_image: preview,
    },
  ],
  promoPoints: [
    {
      coordinates: [56.3196, 43.9464],
      id: 2820,
      promo: 125,
      step: 1,
      type: "promo",
      preview_image: preview,
    },
    {
      coordinates: [56.3256, 43.9582],
      id: 2965,
      promo: 770,
      step: 2,
      type: "promo",
      preview_image: flag,
    },
    {
      coordinates: [56.3348, 43.9568],
      id: 44944,
      promo: 200,
      step: 3,
      type: "promo",
      preview_image: compass,
    },
    {
      coordinates: [56.3279, 43.9568],
      id: 167950,
      promo: 160,
      step: 4,
      type: "promo",
      preview_image: camera,
    },
  ],
  partnersPoints: [
    {
      coordinates: [56.3038, 43.9387],
      id: 3040,
      title: "Ресторан Folk2",
      content: "Кажется, время завтрака?2",
      type: "partners",
    },
    {
      coordinates: [56.3007, 43.9404],
      id: 41454,
      title: "Ресторан Folk",
      content: "Кажется, время завтрака?",
      type: "partners",
    },
  ],
  excursionPoints: [
    {
      coordinates: [56.2929, 43.9352],
      id: 193624,
      content: "Спектакль-променад по Старо-Татарской слободе",
      type: "excursion",
    },
  ],
};

export const newPoints = {
  id: "string",
  type: "string",
  name: "string",
  description: "string",
  latitude: 0,
  longitude: 0,
  attachments: ["string"],
  preview_image: "string",
  address: "string",
  day_number: 0,
  order_number: 0,
  routeId: "string",
  route: "string",
  stories: ["string"],
};
